dist: bionic
language: generic
before_install:
    - wget http://apertium.projectjj.com/apt/install-nightly.sh -O - | sudo bash
    - sudo apt-get install hfst python3-hfst libhfst-dev cg3
    - which python3
    - echo $PYTHONPATH
script:
    - ./autogen.sh
    - ./configure --enable-segmenter --enable-labeled-segments --enable-lemmatiser --enable-hyphenator --enable-ftb3 --with-java
    - make
    - make check
    - cat test/test-suite.log
notifications:
    irc:
        channels:
            - "chat.freenode.net#omorfi"
        on_failure: always
        on_success: always

